# # ATIVIDADE 1
# # Solicita um número ao usuário
# numero = int(input("Digite um número para ver a tabuada: "))

# # Laço for para gerar a tabuada de 1 a 10
# print(f"\nTabuada do {numero}:\n")
# for i in range(1, 11):
#     resultado = numero * i
#     print(f"{numero} x {i} = {resultado}")

# ATIVIDADE 2
# soma = 0
# for i in range(1, 101):
#     soma += i

# print(f"A soma dos números de 1 a 100 é: {soma}")

# ATIVIDADE 3

# palavra = input("Digite uma palavra: ")

# for caractere in palavra:
#     print(caractere)

# ATIVIDADE 4

# for i in range(10, 0, -1):
#     print(i)

# print("Feliz Ano Novo!")
